### PR TITLE
added myxx recipes as an example

### PR DESCRIPTION
**Pull request by ashleycribb**

### CODE REVIEW

**Review by atherdon — APPROVED** [review]

**Comment by atherdon** [comment]
Maybe you can start to talk with companies about partnerships? i mean if we think it will work - why not push this forward right now?

**Comment by ashleycribb** [comment]
True.  The idea that I was thinking as far as business development was to ask for recipes and we would not publish them, but, use that information to find out what the nutritional information is for each meal (for say a restaurant) Then based on partnership level we would highlight their restaurant as a viable place for them to eat and one that they may like)

**Comment by atherdon** [comment]
By recipes here - we talking about meals, right?

**Comment by ashleycribb** [comment]
Yes.  Though we could partner with restaurants as well or grocery stores .. so we could start now, but, have to have a viable product that shows results and people using the product.

**Comment by atherdon** [comment]
Ok, got it. I think we don't need recipes aka step-by-step instructions - for meals we need just set of ingredients/other items - that important for people with diabetes - aka products that diabet-friendly

And i waited when you'll tell that we cannot start to talk with someone outside before we don't have something to show ;)

**Comment by atherdon** [comment]
Let's think then more about what MVP will look like. would database with data is enough for it or we should have frontend side as well? if yes for frontend - what should be displayed there, how many pages, etc...

**Comment by ashleycribb** [comment]
Yeah.  I have been looking into the front end development and user interfaces.  Plus I am talking with a mentor on Saturday about our progress.  I also have contacted a local Certified Diabetic Educator (presently stay at home mom, but, still is a subject matter expert) .. And I am thinking of applying for a grant so that we can have some funds to get the MVP and start obtaining users.  The partnership is a means to obtain data of the business owners so that then we can filter out the nutrients based on the dietary requirements.  We leverage the fact that we have the recipes even privately with the fact that we will have users that will buy their products because of personalization.  Which will be the future of food.

**Comment by ashleycribb** [comment]
What do you think about

https://www.uplabs.com/posts/food-recipe-mobile-app

By the way ultimately I had the idea of a recipe is kind of like a bill of materials.  Recipes throughout the digital age have been text that has been scraped on a list.  But, in the future a recipe will be an item.  So, based on how much you have of something in the recipe you will have to purchase it if you don’t have it at home.  That is what Myxx has done.  They partner with food manufacturers and grocery stores to take recipes and make them shoppable lists so based on who they partner with you can take a recipe and add them to an online shopping cart.  What if we could do that with other stores?

Also in our case with diabetics you should be able to send a recipe to someone and it should check to see if that recipe would work for them based on their preferences.  I am just brainstorming of course, but, that was the thought.

**Comment by ashleycribb** [comment]
A good way to think about a recipe for the future will be like a loot box in a game.  You click on the loot box and depending on what type of character you chose you would obtain a head piece, pants, shoes, armor.  So, everything you need to start your journey with has come with that box.  Then as you gain levels it also gives you those levels as well.  Why can’t a recipe do the same thing?  ;)

**Comment by atherdon** [comment]
> I also have contacted a local Certified Diabetic Educator (presently stay at home mom, but, still is a subject matter expert)

Awesome news. I think we need people from the medical world in order to validate things.

> And I am thinking of applying for a grant so that we can have some funds to get the MVP and start obtaining users.

cool if it will work. I have a friend that was working with PhD at Math guy from US, that received a grant for applying his math program for teaching kids online and form a team in Ukraine(cheap salary). maybe it can work in this case as well.

> We leverage the fact that we have the recipes even privately with the fact that we will have users that will buy their products because of personalization.  Which will be the future of food.

it's a long run. we even don't have resources to run ML scripts frequently. So it's maybe 5-8 stage.

> https://www.uplabs.com/posts/food-recipe-mobile-app

For the last years I saw so much templates like this. I think i told about it at forum thread. So for me they all the same. But I understand that - I was a WP developer a lot of time - and always checking themes that can help to reduce time on it. if it was my choice - only invisionapp template that i shared is excites me. because i know that it top1% work. and i can move it to any designer hands and they can adjust it.

> But, in the future a recipe will be an item. 

I like this vision. But long term thing.

> They partner with food manufacturers and grocery stores to take recipes and make them shoppable lists so based on who they partner with you can take a recipe and add them to an online shopping cart.

It will be awesome. But i think this is also hard to move from the ground. Only maybe investors/mentors with food tech background with long road of connections will be able to do it. Again - i can be wrong - but i'm keeping my head close to the ground right now :) it's totally viable - but without moves into this direction...


My question about recipe vs meal is actually mostly about database structure. i mean that for MVP - that can be shown to restaurant owners(again - as we didn't start it yep - it's only an assumption) meals with ingredient list will be less complex to do.

**Comment by atherdon** [comment]
I think about recipes in the future like this: "I don't want to be worried about food at all - just want to have a warm fresh meal at my table when i want to eat and that i love to eat :)" without grocery shopping, opening the refrigerator, googling recipes, comparing them with my pantry, etc

**Comment by atherdon** [comment]
> That is what Myxx has done.  They partner with food manufacturers and grocery stores

I like an idea to partner with some big names and help them to sell things and get money from them. But from tech point - it'll be a lot of pain. it's even hard to big teams with a budget.

**Comment by ashleycribb** [comment]
Of course this is a long term goal just giving the vision we can go the route you have been going on just giving what my vision is .. you giving yours and we meet in the middle .. I will look at the invision app Template in more detail ..

**Comment by ashleycribb** [comment]
And yes in the future it just maybe we 3d print our food as in science fiction has foretold .. who knows

**Comment by atherdon** [comment]
> 3d print our food 

or at least Amazon Fresh/Uber Eats via Amazon Echo + personal nutrition doctor build with machine learning

**Pull request merged**
