### PR TITLE
new file nutritionalAttributes.json

### PR DESCRIPTION
**Pull request by ronniebhatt**

### CODE REVIEW

**Comment by atherdon** [comment]
looks fine, but why it's was commited here? can you push the same files to groceristar/sd repository as well?

**Comment by ronniebhatt** [comment]
sorry for that

**Comment by atherdon** [comment]
no problem - you actually learning how to work at team and pay some
additional attention - so it's fine

**Comment by ronniebhatt** [comment]
should i add files to GroceriStar/sd repository

**Comment by atherdon** [comment]
yes, please.  i think i replied this before

>

**Pull request merged**
